version: "[]"
updates: "[]"
  - package-ecosystem: "[]"
    directories: "[]"
    schedule: "[]"
      interval: "[]"
    open-pull-requests-limit: "[]"
    ignore: "[]"
      - dependency-name: "[]"
