name: Discord Notify

on:
  pull_request:
    types: [ labeled ]
    
jobs:
  notify:
      if: ${{ github.event.label.name == 'React Core Team' }}
      runs-on: ubuntu-latest
      steps:
        - name: Discord Webhook Action
          uses: tsickert/discord-webhook@v6.0.0
          with:
              webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
              content: "New PR from ${{ github.event.author.login }}: [#${{ github.event.pull_request.title }}](${{ github.event.pull_request.permalink }})"
            